language: go

sudo: false

go:
  - 1.x

notifications:
  email: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_script:
  - echo $PATH
  - echo $GOPATH
  - go version
  - go env
  - go get -v -t ./src/...

script:
  - make test
