program_name: Skynet

program_description: Sowftware 'Skynet' is developed for human extermination (nope)

authors:
  - John Smith
  - Clint Eastwood

years:
  - 2000

license: agpl-3.0

paths:
  - parser/...
  - ai/...
  - execute.c
  - main.c

custom_license_notice: /home/root/notices/license_notice_for_skynet.txt

project_root: /home/root/projects/skynet

add_license_file: false

add_license_notice: true
